#!/bin/bash

# A scrip to run the Blocks Download Logic:
# To run this script you need to have "jclDownload.jar" which can be generated by "gradle packageJClDownload" from
# the "/integration" package in the "bsv-components" project.

num_args=$#
if [ $num_args -lt 2 ] 
then
  # We run the JAR without params, so the Java code will print the Help page:
  nohup java -jar jclDownload.jar > downloadFullLog.log &
else 
  # We run the JAR with all the params:
  nohup java -jar jclDownload.jar $1 $2 $3 $4 > downloadFullLog.log &
fi
