package io.bitcoinsv.bsvcl.net.unit.protocol.serialization


import io.bitcoinsv.bsvcl.common.bytes.ByteArrayReader
import io.bitcoinsv.bsvcl.common.bytes.ByteArrayWriter
import io.bitcoinsv.bitcoinjsv.core.Utils
import io.bitcoinsv.bitcoinjsv.params.MainNetParams
import io.bitcoinsv.bitcoinjsv.params.Net
import spock.lang.Specification

/**
 * Testing class for the VarIntMSg Message Serialization.
 * The test is taken the assumption that we have already a correct serialization version of this Message, obtained
 * from another source that we trust (in this case the Java BitcoinJ library). So we serialize/deserialize some
 * messages with out code and compare the results with that reference.
 */
class VarIntSerializationSpec extends Specification {

    // This is a VarInt  Serialized in HEX format, generated by a third party (bitcoinJ)
    // The following Serialized value for an Address has been produced using:
    // - value: 543

    private static final String REF_VARINT_MSG = "fd1f02"
    private static final int VAR_VALUE = 543

    def "Testing VarInt Deserializing"(int byteInterval, int delayMs) {
        given:
            io.bitcoinsv.bsvcl.net.protocol.config.ProtocolConfig config = io.bitcoinsv.bsvcl.net.protocol.config.ProtocolConfigBuilder.get(new MainNetParams(Net.MAINNET))
            io.bitcoinsv.bsvcl.net.protocol.serialization.common.DeserializerContext context = io.bitcoinsv.bsvcl.net.protocol.serialization.common.DeserializerContext.builder()
                    .protocolBasicConfig(config.getBasicConfig())
                    .build()
            io.bitcoinsv.bsvcl.net.protocol.serialization.VarIntMsgSerializer serializer = io.bitcoinsv.bsvcl.net.protocol.serialization.VarIntMsgSerializer.getInstance()
            io.bitcoinsv.bsvcl.net.protocol.messages.VarIntMsg message = null
            ByteArrayReader byteReader = io.bitcoinsv.bsvcl.net.unit.protocol.tools.ByteArrayArtificalStreamProducer.stream(Utils.HEX.decode(REF_VARINT_MSG), byteInterval, delayMs)
        when:
            message = serializer.deserialize(context, byteReader)
        then:
            message.getValue() == VAR_VALUE
        where:
            byteInterval | delayMs
                20       |   2
    }

    def "Testing VarInt Serializing"() {
        given:
            io.bitcoinsv.bsvcl.net.protocol.config.ProtocolConfig config = io.bitcoinsv.bsvcl.net.protocol.config.ProtocolConfigBuilder.get(new MainNetParams(Net.MAINNET))
            io.bitcoinsv.bsvcl.net.protocol.serialization.common.SerializerContext context = io.bitcoinsv.bsvcl.net.protocol.serialization.common.SerializerContext.builder()
                    .protocolBasicConfig(config.getBasicConfig())
                    .build()
            io.bitcoinsv.bsvcl.net.protocol.messages.VarIntMsg message = io.bitcoinsv.bsvcl.net.protocol.messages.VarIntMsg.builder().value(VAR_VALUE).build()
            io.bitcoinsv.bsvcl.net.protocol.serialization.VarIntMsgSerializer serializer = io.bitcoinsv.bsvcl.net.protocol.serialization.VarIntMsgSerializer.getInstance()
            String messageBytesStr = null
        when:
            ByteArrayWriter byteWriter = new ByteArrayWriter()
            serializer.serialize(context, message, byteWriter)
            byte[] messageBytes = byteWriter.reader().getFullContent()
            messageBytesStr = Utils.HEX.encode(messageBytes)
        then:
            messageBytesStr.equals(REF_VARINT_MSG)
    }

    /**
     * We test that the VarIntMsg Serializer works fine for numbers higher than 4GB
     */
    def "Testing big number (>4GB)"() {
        given:
            long number = 5_000_000_000; // 5GB
        when:
            // We Serialize the MSg:
            io.bitcoinsv.bsvcl.net.protocol.config.ProtocolConfig config = io.bitcoinsv.bsvcl.net.protocol.config.ProtocolConfigBuilder.get(new MainNetParams(Net.MAINNET))
            io.bitcoinsv.bsvcl.net.protocol.serialization.common.SerializerContext serContext = io.bitcoinsv.bsvcl.net.protocol.serialization.common.SerializerContext.builder()
                .protocolBasicConfig(config.getBasicConfig())
                .build()
            io.bitcoinsv.bsvcl.net.protocol.messages.VarIntMsg msg = io.bitcoinsv.bsvcl.net.protocol.messages.VarIntMsg.builder().value(number).build()
            ByteArrayWriter writer = new ByteArrayWriter()
            io.bitcoinsv.bsvcl.net.protocol.serialization.VarIntMsgSerializer.getInstance().serialize(serContext, msg, writer)
            byte[] numberBytes = writer.reader().getFullContentAndClose()

            // We deserialize the msg:
            io.bitcoinsv.bsvcl.net.protocol.serialization.common.DeserializerContext desContext = io.bitcoinsv.bsvcl.net.protocol.serialization.common.DeserializerContext.builder()
                .protocolBasicConfig(config.getBasicConfig())
                .build()
            ByteArrayReader reader = new ByteArrayReader(numberBytes)
            io.bitcoinsv.bsvcl.net.protocol.messages.VarIntMsg msgDes = io.bitcoinsv.bsvcl.net.protocol.serialization.VarIntMsgSerializer.getInstance().deserialize(desContext, reader)

        then:
            msg.equals(msgDes)
    }
}
