# Perform all tests on pull requests and the main branch
name: Check PR
permissions:
  checks: write
  pull-requests: write
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  run-check:
    timeout-minutes: 20
    runs-on: linux

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run All Tests
        run: ./gradlew test integrationTest jacocoTestReport
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            **/test-results/**/*.xml
