# Perform tests on branches other than the main branch
name: Check non-main branches

on:
  push:
    branches:
      - '*'
      - '!main'
  workflow_dispatch:

jobs:
  run-check:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run Unit Tests
        run: ./gradlew check jacocoTestReport
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
